apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dp-1
  template:
    metadata:
      labels:
        app: nginx-dp
    spec:
      containers:
      - name: nginx
        image: harbor.lab.local/ocp/nginx-test:1.0
